import { Bike } from "../types";

export const getGeomtries = (): Bike[] => {
  return [
    {
      manufacturer: "Cannondale",
      model: "SuperSix EVO LAB71",
      year: 2025,
      sizes: [
        {
          frameSize: 44,
          seatTubeLength: 40.0,
          topTubeHorizontal: 51.2,
          topTubeActual: 46.9,
          headTubeAngle: 70.9,
          seatTubeAngle: 74.3,
          standover: 69.8,
          headTubeLength: 10.0,
          wheelbase: 98.1,
          frontCenter: 58.2,
          chainStayLength: 41.0,
          bottomBracketDrop: 7.4,
          bottomBracketHeight: 26.8,
          forkRake: 5.5,
          trail: 6.0,
          stack: 50.5,
          reach: 37.0,
        },
        {
          frameSize: 48,
          seatTubeLength: 43.8,
          topTubeHorizontal: 52.0,
          topTubeActual: 47.9,
          headTubeAngle: 71.2,
          seatTubeAngle: 74.3,
          standover: 72.7,
          headTubeLength: 11.4,
          wheelbase: 98.7,
          frontCenter: 58.9,
          chainStayLength: 41.0,
          bottomBracketDrop: 7.4,
          bottomBracketHeight: 26.8,
          forkRake: 5.5,
          trail: 5.8,
          stack: 52.0,
          reach: 37.4,
        },
        {
          frameSize: 51,
          seatTubeLength: 47.7,
          topTubeHorizontal: 52.8,
          topTubeActual: 48.9,
          headTubeAngle: 71.2,
          seatTubeAngle: 74.3,
          standover: 75.6,
          headTubeLength: 13.0,
          wheelbase: 99.6,
          frontCenter: 59.8,
          chainStayLength: 41.0,
          bottomBracketDrop: 7.4,
          bottomBracketHeight: 26.8,
          forkRake: 5.5,
          trail: 5.8,
          stack: 53.5,
          reach: 37.8,
        },
        {
          frameSize: 54,
          seatTubeLength: 51.5,
          topTubeHorizontal: 54.6,
          topTubeActual: 50.9,
          headTubeAngle: 71.2,
          seatTubeAngle: 73.7,
          standover: 78.8,
          headTubeLength: 15.4,
          wheelbase: 101.0,
          frontCenter: 61.1,
          chainStayLength: 41.0,
          bottomBracketDrop: 7.2,
          bottomBracketHeight: 27.1,
          forkRake: 5.5,
          trail: 5.8,
          stack: 55.5,
          reach: 38.4,
        },
      ],
    },
    {
      manufacturer: "Quick Pro",
      model: "ER:ONE",
      year: 2025,
      sizes: [
        {
          frameSize: 430,
          seatTubeLength: 43.0,
          topTubeHorizontal: 51.5,
          headTubeAngle: 70.0,
          seatTubeAngle: 75.0,
          standover: 74.6,
          headTubeLength: 10.5,
          wheelbase: 98.5,
          chainStayLength: 40.8,
          bottomBracketDrop: 7.0,
          stack: 50.5,
          reach: 38.0,
        },
      ],
    },
  ];
};
